In [19]:
#Pre datasets for MetaBrain-Expression

In [20]:
import scanpy as sc
import numpy as np
import pandas as pd

In [21]:
import magic

In [22]:
ad=sc.read('./scrna_FC_processed.h5ad')
ad

AnnData object with n_obs × n_vars = 19639 × 65217
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'ct', 'diagnosis', 'region', 'seq_type', 'platform', 'bc', 'doublet_score', 'RNA_snn_res.0.5', 'seurat_clusters', 'label', 'col'
    var: 'features'

In [23]:
sc.pp.normalize_total(ad, target_sum = 1e5)

In [24]:
sc.pp.log1p(ad, base = 2)
df_adata = pd.DataFrame(ad.X.todense(), columns = ad.var_names, index = ad.obs_names)
df_adata

,DDX11L1,WASH7P,MIR6859-3,RP11-34P13.3,MIR1302-9,FAM138A,OR4G4P,OR4G11P,OR4F5,RP11-34P13.7,...,MT-ND4,MT-TH,MT-TS2,MT-TL2,MT-ND5,MT-ND6,MT-TE,MT-CYB,MT-TT,MT-TP
AAACCTGAGATGGCGT-1_4341_BA46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0
AAACCTGAGCTAACTC-1_4341_BA46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.764986,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0
AAACCTGAGTGTTAGA-1_4341_BA46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.491477,0.0,0.0,0.0,3.058555,0.000000,0.0,5.234842,0.0,0.0
AAACCTGCACCCATTC-1_4341_BA46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.157306,0.0,0.0,0.0,4.612214,0.000000,0.0,3.670028,0.0,0.0
AAACCTGTCTCATTCA-1_4341_BA46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTACTGCATACGCCG-1_5976_BA9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.793370,0.0,0.0,0.0,4.005150,3.464426,0.0,7.092915,0.0,0.0
TTTACTGTCTCTGCTG-1_5976_BA9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.666931,0.0,0.0,0.0,6.359132,0.000000,0.0,7.932330,0.0,0.0
TTTCCTCCACACATGT-1_5976_BA9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.392468,0.0,0.0,0.0,5.296888,0.000000,0.0,5.702721,0.0,0.0
TTTCCTCGTTCAGTAC-1_5976_BA9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0
TTTGTCACATTACGAC-1_5976_BA9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,6.718023,0.0,0.0

In [ ]:
#MAGIC

In [25]:
magic_op = magic.MAGIC()
df_adata_magic = magic_op.fit_transform(df_adata)

Calculating MAGIC...
  Running MAGIC on 19639 cells and 65217 genes.
  Calculating graph and diffusion operator...

/home/ggj/anaconda3/envs/scvi-env/lib/python3.9/site-packages/magic/magic.py:425: UserWarning: Input matrix contains unexpressed genes. Please remove them prior to running MAGIC.
  warnings.warn(

    Calculating PCA...
    Calculated PCA in 103.91 seconds.
    Calculating KNN search...
    Calculated KNN search in 32.38 seconds.
    Calculating affinities...
    Calculated affinities in 29.37 seconds.
  Calculated graph and diffusion operator in 192.52 seconds.
  Running MAGIC with `solver='exact'` on 65217-dimensional data may take a long time. Consider denoising specific genes with `genes=<list-like>` or using `solver='approximate'`.
  Calculating imputation...
  Calculated imputation in 165.05 seconds.
Calculated MAGIC in 364.31 seconds.

In [26]:
df_adata_magic2 = df_adata_magic*100
df_adata_magic2 = df_adata_magic2.astype(int)
df_adata_magic2 = df_adata_magic2/100

In [27]:
adata_magic2 = sc.AnnData(df_adata_magic2)

In [28]:
df_adata_magic2

,DDX11L1,WASH7P,MIR6859-3,RP11-34P13.3,MIR1302-9,FAM138A,OR4G4P,OR4G11P,OR4F5,RP11-34P13.7,...,MT-ND4,MT-TH,MT-TS2,MT-TL2,MT-ND5,MT-ND6,MT-TE,MT-CYB,MT-TT,MT-TP
AAACCTGAGATGGCGT-1_4341_BA46,0.0,0.06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,2.31,0.0,0.0,0.0,0.82,0.10,0.0,1.46,0.0,0.0
AAACCTGAGCTAACTC-1_4341_BA46,0.0,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,2.27,0.0,0.0,0.0,0.51,0.10,0.0,1.32,0.0,0.0
AAACCTGAGTGTTAGA-1_4341_BA46,0.0,0.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.01,...,5.49,0.0,0.0,0.0,2.91,0.64,0.0,4.51,0.0,0.0
AAACCTGCACCCATTC-1_4341_BA46,0.0,0.26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.01,...,4.61,0.0,0.0,0.0,2.57,0.68,0.0,3.97,0.0,0.0
AAACCTGTCTCATTCA-1_4341_BA46,0.0,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.02,...,1.70,0.0,0.0,0.0,0.58,0.05,0.0,1.07,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTACTGCATACGCCG-1_5976_BA9,0.0,0.22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,7.16,0.0,0.0,0.0,4.28,1.63,0.0,5.90,0.0,0.0
TTTACTGTCTCTGCTG-1_5976_BA9,0.0,0.21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,7.16,0.0,0.0,0.0,4.30,0.82,0.0,6.33,0.0,0.0
TTTCCTCCACACATGT-1_5976_BA9,0.0,0.14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,6.21,0.0,0.0,0.0,3.03,0.45,0.0,5.43,0.0,0.0
TTTCCTCGTTCAGTAC-1_5976_BA9,0.0,0.03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,1.77,0.0,0.0,0.0,0.72,0.10,0.0,1.29,0.0,0.0
TTTGTCACATTACGAC-1_5976_BA9,0.0,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,2.02,0.0,0.0,0.0,0.85,0.07,0.0,1.48,0.0,0.0

In [29]:
y1=np.array(df_adata_magic2.T)

In [31]:
anno=ad.obs
anno

,orig.ident,nCount_RNA,nFeature_RNA,ct,diagnosis,region,seq_type,platform,bc,doublet_score,RNA_snn_res.0.5,seurat_clusters,label,col
AAACCTGAGATGGCGT-1_4341_BA46,0,1121.0,792,AST-PP,Control,PFC,snRNA-seq,10x,AAACCTGAGATGGCGT-1_4341_BA46,0.035064,2,2,2_AST-PP,#D51F26
AAACCTGAGCTAACTC-1_4341_BA46,0,928.0,658,Oligodendrocytes,Control,PFC,snRNA-seq,10x,AAACCTGAGCTAACTC-1_4341_BA46,0.035605,0,0,0_Oligodendrocytes,#F8B114
AAACCTGAGTGTTAGA-1_4341_BA46,0,13640.0,4890,L5/6,Control,PFC,snRNA-seq,10x,AAACCTGAGTGTTAGA-1_4341_BA46,0.066727,18,18,18_L5/6,#963B2B
AAACCTGCACCCATTC-1_4341_BA46,0,8526.0,3967,L2/3,Control,PFC,snRNA-seq,10x,AAACCTGCACCCATTC-1_4341_BA46,0.105855,4,4,4_L2/3,#4BAF98
AAACCTGTCTCATTCA-1_4341_BA46,0,846.0,621,Microglia,Control,PFC,snRNA-seq,10x,AAACCTGTCTCATTCA-1_4341_BA46,0.010448,8,8,8_Microglia,#22694E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTACTGCATACGCCG-1_5976_BA9,0,19924.0,6057,L5/6,Control,PFC,snRNA-seq,10x,TTTACTGCATACGCCG-1_5976_BA9,0.085537,20,20,20_L5/6,#963B2B
TTTACTGTCTCTGCTG-1_5976_BA9,0,6166.0,2903,IN-PV,Control,PFC,snRNA-seq,10x,TTTACTGTCTCTGCTG-1_5976_BA9,0.059473,11,11,11_IN-PV,#B88EC1
TTTCCTCCACACATGT-1_5976_BA9,0,15661.0,4775,L5/6-CC,Control,PFC,snRNA-seq,10x,TTTCCTCCACACATGT-1_5976_BA9,0.080621,13,13,13_L5/6-CC,#42403E
TTTCCTCGTTCAGTAC-1_5976_BA9,0,714.0,525,OPC,Control,PFC,snRNA-seq,10x,TTTCCTCGTTCAGTAC-1_5976_BA9,0.011338,1,1,1_OPC,#9FABAA
TTTGTCACATTACGAC-1_5976_BA9,0,959.0,711,OPC,Control,PFC,snRNA-seq,10x,TTTGTCACATTACGAC-1_5976_BA9,0.024977,1,1,1_OPC,#9FABAA

In [32]:
anno['cell_type']=anno['ct']

In [34]:
argidx = anno.cell_type.values.argsort()

anno = anno.iloc[argidx,:]
y_pb1 = y1[:, argidx]

In [35]:
y_pb1.shape

(65217, 19639)

In [36]:
cluster_name, cnt = np.unique(anno.cell_type.values, return_counts=True)
cumcnt = np.cumsum(cnt)[:-1]

In [37]:
y_pb1 = np.split(y_pb1, cumcnt, axis=1)
y_pb1 = np.array([tmp.mean(-1) for tmp in y_pb1]).T

In [41]:
import pandas as pd
exp=pd.DataFrame(y_pb1,index=ad.var_names,columns=cluster_name)
exp

,AST-PP,IN-PV,IN-SST,IN-SV2C,IN-VIP,L2/3,L4,L5/6,L5/6-CC,Microglia,OPC,Oligodendrocytes
DDX11L1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
WASH7P,0.123136,0.156127,0.173884,0.221039,0.170023,0.186092,0.240504,0.192655,0.226548,0.078538,0.060653,0.042938
MIR6859-3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
RP11-34P13.3,0.000000,0.002255,0.000029,0.000000,0.000000,0.003884,0.002251,0.003100,0.002268,0.000000,0.000000,0.000000
MIR1302-9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
MT-ND6,0.078342,0.668662,0.351375,0.488483,0.338227,0.590447,0.571153,0.549528,0.683096,0.062900,0.136474,0.070176
MT-TE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
MT-CYB,1.869700,4.508285,4.058480,4.450702,3.867831,4.499810,4.249127,4.417264,4.692368,1.424969,1.987037,1.524643
MT-TT,0.000000,0.000000,0.000000,0.000000,0.000000,0.001582,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
MT-TP,0.000000,0.007120,0.000356,0.000674,0.000023,0.000717,0.002822,0.000000,0.000000,0.000000,0.000000,0.000000

In [42]:
exp.to_csv('./exp.csv')